---
title: "Using crisprapex"
author: Aditya Bhagwat
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{finding_flank_cas9s}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

crisprapex makes the design of CRISPR-APEX experiments easier.
Serving to the specifics of such experiments, these functions:

* Find a CRISPR **set** to target a genomic **set**.
* Allow to target the **flanks** of genomic loci rather than loci themselves.
* Are **efficient**, building on top of data.table and Biostrings.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "    #"
)
```

# Finding cas9 sites to target TF binding flanks

```{r setup}
library(magrittr)
library(crisprapex)
bsgenome <- BSgenome.Mmusculus.UCSC.mm10::Mmusculus

bedfile <- system.file('extdata/SRF_sites.bed', package = 'crisprapex')
tbranges <- read_bed(bedfile, verbose = FALSE) %>% extract(1:30)

flank9s  <- tbranges %>% flank_fourways() %>% findcas9s(bsgenome)
center9s <- tbranges %>% slop_fourways()  %>% findcas9s(bsgenome)
cas9dt   <- flank9s  %>% rm_taboo_cas9s(center9s)
```
